DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS logger;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS project_info;
DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS action_plan;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  password TEXT NOT NULL,
  project INTEGER,
  role TEXT NOT NULL,
  verified INTEGER
);

CREATE TABLE project (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description TEXT UNIQUE NOT NULL,
  init DATE NOT NULL,
  end DATE NOT NULL,
  status INTEGER NOT NULL
);

CREATE TABLE logger (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event TEXT NOT NULL,
  date TEXT NOT NULL,
  user TEXT NOT NULL
);

CREATE TABLE client (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dni TEXT UNIQUE NOT NULL,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  birthdate DATE NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  address TEXT NOT NULL
);

CREATE TABLE car (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  plaque TEXT UNIQUE NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  year INTEGER NOT NULL,
  serial_car TEXT UNIQUE NOT NULL,
  serial_mot TEXT UNIQUE NOT NULL,
  color TEXT NOT NULL,
  issue TEXT NOT NULL,
  owner TEXT NOT NULL
);

CREATE TABLE department(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE project_info(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  car_id TEXT NOT NULL,
  department TEXT NOT NULL,
  manager INTEGER NOT NULL,
  problem TEXT NOT NULL,
  solution TEXT NOT NULL,
  ammount REAL NOT NULL,
  obs TEXT
);

CREATE TABLE metrics(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dimentions INTEGER NOT NULL,
  units TEXT NOT NULL
);

CREATE TABLE action_plan(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_info_id INTEGER NOT NULL,
  action TEXT NOT NULL,
  activity TEXT NOT NULL,
  init DATE NOT NULL,
  end DATE NOT NULL,
  category TEXT NOT NULL,
  material TEXT NOT NULL,
  metric INTEGER NOT NULL,
  human_quantity INTEGER NOT NULL,
  hours_quantity INTEGER NOT NULL,
  material_quantity INTEGER NOT NULL,
  responsable TEXT NOT NULL,
  human_ammount REAL NOT NULL,
  material_ammount REAL NOT NULL
);